import { AssessmentTrendChart } from "@/components/AssessmentTrendChart";
import { ReportDownloadButton, SessionAudioButton } from "@/components/ReadingActions";
import { BookOpen, Check, Headphones, Mic, Sparkles, Star } from "lucide-react";
import { useState } from "react";

function Stat({ value, label, color, icon }: { value: string | number; label: string; color: string; icon: React.ReactNode }) { return <div className="stat-card" style={{ "--card": color } as React.CSSProperties}><div className="stat-icon">{icon}</div><strong>{value}</strong><span>{label}</span></div>; }

export function ParentDashboard({ data, loading, onReadTogether }: { data: any; loading: boolean; onReadTogether: () => void }) {
  const child = data?.children?.[0];
  const summary = child?.summary;
  const displayName = child?.displayName ?? "Amina";
  const latest = child?.sessions?.[0];
  const [completed, setCompleted] = useState<Record<number, boolean>>({});
  const checklist = [<><b>Choose a paragraph</b> and let {displayName} decide where to begin.</>, <>Listen for <b>{summary?.practiceWords?.slice(0, 3).join(", ") || "today’s interesting words"}</b> together.</>, <>Ask what picture the story made in their mind, then <b>celebrate the answer.</b></>];
  return <div className="view-wrap parent-view"><section className="dashboard-head"><div><div className="kicker">Family Reading Space</div><h1 className="dashboard-title">Cheer the<br /><span className="marker">small wins.</span></h1><p className="dashboard-subtitle">You do not need to be a teacher. Your calm encouragement, curiosity, and five focused minutes can help reading feel safe and enjoyable.</p></div><span className="view-chip">{loading ? "Loading progress" : `${displayName}'s reading`}</span></section><section className="stat-grid parent-stat-grid"><Stat value={`${child?.minutesReadThisWeek ?? 0} min`} label="Minutes Read This Week" color="#dfe7ff" icon={<Headphones size={21} />} /><Stat value="Persistent Reader" label={`${summary?.sessionsCompleted || 0} reading sessions`} color="#f4c746" icon={<Sparkles size={21} />} /><Stat value={`${summary?.sessionsCompleted || 0} Stories Shared`} label="Reading moments together" color="#d9f0e5" icon={<BookOpen size={21} />} /><Stat value="Kind Coach" label="Encouragement matters" color="#ffdcd4" icon={<Star size={21} />} /></section><AssessmentTrendChart title={`${displayName}'s monthly reading trend`} points={child?.assessmentTrend || []} compact /><section className="dashboard-grid"><article className="dashboard-card"><div className="card-title-row"><h2>{displayName}'s strengths</h2><span>Recent reading</span></div><div className="tip-list"><div className="tip"><span><Check size={13} /></span><div><b>Self-correction</b><br />Trying a word again is a confident reader move.</div></div><div className="tip"><span><Check size={13} /></span><div><b>Story sharing</b><br />Talking about details builds understanding.</div></div><div className="tip"><span><Check size={13} /></span><div><b>Brave persistence</b><br />Finishing a story builds reading stamina.</div></div></div></article><article className="dashboard-card practice-checklist"><div className="card-title-row"><h2>Practise together</h2><span>5 friendly minutes</span></div><div>{checklist.map((step, index) => <label className={completed[index] ? "complete" : ""} key={index}><input type="checkbox" checked={Boolean(completed[index])} onChange={() => setCompleted(current => ({ ...current, [index]: !current[index] }))} /><span>{index + 1}</span><div>{step}</div><Check size={17} /></label>)}</div><div className="practice-actions"><button className="primary-cta" onClick={onReadTogether}><Mic size={18} /> Read together</button></div></article></section>{child?.childProfileId && <div className="role-report-row"><div><b>Share a clear progress summary</b><span>Download a parent-friendly snapshot to discuss with the teacher.</span></div><div><ReportDownloadButton childProfileId={child.childProfileId} audience="parent" label="Download parent summary" />{latest?.audioStorageKey && <SessionAudioButton sessionId={latest.id} label="Play last recording" />}</div></div>}</div>;
}
